// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwgGGGGsyfLyJga6KSk5yV4gF3BPLPxo',
    appId: '1:617662759534:web:27c2683c9a788e54e09c7f',
    messagingSenderId: '617662759534',
    projectId: 'alt-f4-kitahack',
    authDomain: 'alt-f4-kitahack.firebaseapp.com',
    storageBucket: 'alt-f4-kitahack.firebasestorage.app',
    measurementId: 'G-Z2147QBBFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXoI9VeFXDNkiBMl8GBAZTLHzAjDUjFRY',
    appId: '1:617662759534:android:afb5d351323bf29de09c7f',
    messagingSenderId: '617662759534',
    projectId: 'alt-f4-kitahack',
    storageBucket: 'alt-f4-kitahack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6uSVOcQg6XQyXsk486GcHwNVx9mzD5s',
    appId: '1:617662759534:ios:7149fc20c887e11ee09c7f',
    messagingSenderId: '617662759534',
    projectId: 'alt-f4-kitahack',
    storageBucket: 'alt-f4-kitahack.firebasestorage.app',
    iosBundleId: 'com.example.altF4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW6uSVOcQg6XQyXsk486GcHwNVx9mzD5s',
    appId: '1:617662759534:ios:7149fc20c887e11ee09c7f',
    messagingSenderId: '617662759534',
    projectId: 'alt-f4-kitahack',
    storageBucket: 'alt-f4-kitahack.firebasestorage.app',
    iosBundleId: 'com.example.altF4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFwgGGGGsyfLyJga6KSk5yV4gF3BPLPxo',
    appId: '1:617662759534:web:b7d459ebe42b21ade09c7f',
    messagingSenderId: '617662759534',
    projectId: 'alt-f4-kitahack',
    authDomain: 'alt-f4-kitahack.firebaseapp.com',
    storageBucket: 'alt-f4-kitahack.firebasestorage.app',
    measurementId: 'G-4LJXLDBKPC',
  );
}
